runtime: nodejs20
env: standard

instance_class: F2

# Resource settings
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 30

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  NODE_ENV: "production"
  REACT_APP_FIREBASE_API_KEY: "YOUR_FIREBASE_API_KEY"
  REACT_APP_FIREBASE_AUTH_DOMAIN: "verifiai.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID: "verifiai"
  REACT_APP_FIREBASE_STORAGE_BUCKET: "verifiai.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "YOUR_MESSAGING_SENDER_ID"
  REACT_APP_FIREBASE_APP_ID: "YOUR_APP_ID"
  REACT_APP_FIREBASE_MEASUREMENT_ID: "YOUR_MEASUREMENT_ID"
  REACT_APP_BACKEND_URL: "https://backend-dot-verifiai.uc.r.appspot.com"

handlers:
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always 