runtime: nodejs20
env: standard

instance_class: F2

# Resource settings
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 30

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Updated health check configuration
liveness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

env_variables:
  NODE_ENV: "production"
  HUGGINGFACE_API_KEY: "Yhf_maFRKvyiimUzQfhGPUlVlWFOdxbUOGOBQN"
  FIREBASE_PROJECT_ID: "verifiai"
  FIREBASE_STORAGE_BUCKET: "verifiai.appspot.com"
  FIREBASE_DATABASE_URL: "https://verifiai.firebaseio.com"
  UPLOAD_DIR: "/tmp/uploads"
  PYTHONPATH: "/app/venv/lib/python3.9/site-packages"
  # Add other environment variables as needed

handlers:
  - url: /.*
    script: auto
    secure: always

# Custom runtime configuration
runtime_config:
  python_version: "3.9"
  entrypoint: |
    # Install Python dependencies
    pip install -r requirements.txt
    
    # Start the Node.js application
    exec node server.js

# Include Firebase service account key
service_account: firebase-adminsdk-fbsvc@verifiai.iam.gserviceaccount.com 